module.exports = {
  source: ['sd-input/src/sd-input.js'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return ['Do not edit directly, this file was auto-generated'];
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};
